### ISSUE TITLE
Footer and header span width of page

### ISSUE THREAD

**Issue by mameehan5** [ctowery/tesla_website2019_dev#3]

**Comment by ctowery** [comment]
Mike, do you mean the black background of the footer/header, or the margins of the icons and text? On my computer the black spans the screen and the icons/text are aligned with the margins for each homepage widget.

**Comment by mameehan5** [comment]
Does the black footer background span the page? The header I made it look like it by specifying that background black. We must need to just make the homepage span the full screen and add a margin around it (for readability). Then the black footer will span the width.

**Comment by ctowery** [comment]
Oh yeah, nm, I don't know why I thought the footer's black background was spanning the page. I think I can fix that real quick

**Comment by ctowery** [comment]
Oh snap, the webpage has a white background on Safari and a dark gray background on Chrome. 
*Sigh*

**Comment by ctowery** [comment]
Also the `sticky-top`class works in Chrome but not Safari, BOOOO!

**Comment by mameehan5** [comment]
Oh goodness. I did not think that we would be having issues that spanned different browsers. Not a fan of that.

**Comment by ctowery** [comment]
Ok, I apparently screwed up associating a particular commit with fixing this issue, so just know there is a commit that resolves the footer problem by creating a new top-level GoHTML script, `/layouts/_default/baseof.html`, which overrides `/themes/academic/layouts/_default/baseof.html`
